[package]
name = "currency"
version = "0.1.0"
edition = "2025"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json", "native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
